### PR TITLE
try from https://github.com/Balazs23/devcontainers-features

### LINKED ISSUE #2: Make it work on the Ubuntu base image
Right now it appears to only work on the Debian PLAIN image
image

https://github.com/devcontainers-community/features-bazel/actions/workflows/test-feature.yml

@mering found another existing Bazel feature https://github.com/Balazs23/devcontainers-features/blob/main/src/bazel/install.sh that might be worth trying to just copy-paste and see if that works? 🤔

### PR DESCRIPTION
**Pull request by jcbhmr**
see if this works on the test matrix. right now its:

```yml
- image: mcr.microsoft.com/devcontainers/base:ubuntu
  options: '{ "bazelisk": "v1.14.0" }'
- image: debian:bookworm-slim
```

### CODE REVIEW

**Comment by jcbhmr** [comment]
well look at that! it works!

**Comment by jcbhmr** [comment]
and yes version pinning works

image
image

**Comment by mering** [comment]
What are you doing? Don't just arbitrarily merge and revert stuff especially without review!

**Comment by jcbhmr** [comment]
yeah i realized that as soon as i merged it. my bad. 😔

**Pull request merged**
